### ISSUE TITLE
Percent sign being removed in CSS Calc()

### ISSUE THREAD

**Issue by maxresnikoff** [Josee9988/MinifyAllCli#61]
This
width: calc(100% - 60px);

Is being minified to this: 
width:calc(100 - 60px);

Not sure if this is a bug or a setting, but I can't find this as a setting to change.

**Comment by maxresnikoff** [comment]
Speedy! Many thanks for the fix

**Comment by Josee9988** [comment]
MinifyAll v2.5.11 is published, it will show in the marketplace in a few minutes, so just wait a couple of mins and install the new update. Thanks!!
